title: WY Chow Lab
url: "https://www.wychowlab.org"
baseurl: ""
tagline: Using magnetic resonance to deliver new insight to human health and disease.
description: We use solid-state NMR spectroscopy to bring new insight to biomolecules in the extracellular matrix that are relevant to human health and disease. We are based at the University of Warwick, UK. 

# seo-tag info
author:
  twitter: wingyingchow
  name: Wing Ying Chow
  image: /img/people/ying.jpg
twitter:
  username: wingyingchow
  card: summary_large_image
social:
  name: Wing Ying Chow
  links: 
    - https://twitter.com/wingyingchow
    - https://orcid.org/0000-0003-0719-5958
    - https://scholar.google.com/citations?user=IIFksEIAAAAJ&hl=en
    - https://www.linkedin.com/in/wingyingchow/
    - https://www.researchgate.net/profile/Wing-Ying-Chow
    - https://github.com/selkieupsilon
locale: en_GB
logo: /img/logo.png

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: 
  - key: collab
    name: Collaborators

# Number of news stories on the front page.
front_page_news: 5

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /#people
  - title: Research
    link: /research.html
  - title: Publications
    link: /publications.html
  - title: Join
    link: /join.html

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
- Makefile
- README.md
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/